import type { NextPage } from 'next';
import Head from 'next/head';
import EmojiFortune from '../components/EmojiFortune';
import Footer from '../components/Footer';

import styles from '../styles/Main.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.mainContainer}>
			<Head>
				<title>emoji fortune</title>
				<meta name="Emoji Fortune" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
    		<EmojiFortune />
			</main>
			<footer>
				<Footer />
			</footer>
    </div>
  );
};

export default Home;
